coverage:
  status:
    project:
      default:
        # basic
        target: 3
        threshold: null
        base: auto
        # advanced
        only_pulls: false

comment:
  layout: "header, diff, changes"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  branches: null
  flags: null
  paths: null
